import coffee from "./assets/img/coffee.webp";
import pastries from "./assets/img/pastries.webp";
export const MENU = [
  {
    id: "esp",
    cat: "Espresso",
    name: "Espresso",
    desc: "Single shot, dark crema, served in a warm porcelain demitasse.",
    price: 3.25,
    image: coffee,
  },
  {
    id: "dop",
    cat: "Espresso",
    name: "Doppio",
    desc: "Double espresso for the unhurried morning.",
    price: 4.0,
    image: coffee,
  },
  {
    id: "mac",
    cat: "Espresso",
    name: "Macchiato",
    desc: "Espresso 'marked' with a small dollop of steamed milk foam.",
    price: 3.75,
    image: coffee,
  },
  {
    id: "cor",
    cat: "Espresso",
    name: "Caffè Corretto",
    desc: "Espresso 'corrected' with a splash of grappa or sambuca.",
    price: 5.5,
    image: coffee,
  },
  {
    id: "cap",
    cat: "Milk Drinks",
    name: "Cappuccino",
    desc: "Equal parts espresso, steamed milk, and velvet foam. Mornings only.",
    price: 4.75,
    image: coffee,
  },
  {
    id: "lat",
    cat: "Milk Drinks",
    name: "Caffè Latte",
    desc: "Long pull of espresso under silky steamed milk.",
    price: 5.25,
    image: coffee,
  },
  {
    id: "fla",
    cat: "Milk Drinks",
    name: "Flat White",
    desc: "Two ristretto shots, microfoam poured close.",
    price: 5.0,
    image: coffee,
  },
  {
    id: "moc",
    cat: "Milk Drinks",
    name: "Mocha",
    desc: "Espresso, steamed milk, and house-made dark chocolate.",
    price: 5.75,
    image: coffee,
  },
  {
    id: "g-co",
    cat: "Granita",
    name: "Granita di Caffè",
    desc: "Our signature. Slow-frozen espresso ice with a crown of unsweetened panna. The reason you walked in.",
    price: 7.5,
    hero: true,
    image: coffee,
  },
  {
    id: "g-li",
    cat: "Granita",
    name: "Granita di Limone",
    desc: "Sicilian lemons, pure and bracing.",
    price: 6.5,
    image: coffee,
  },
  {
    id: "g-al",
    cat: "Granita",
    name: "Granita di Mandorla",
    desc: "Almond milk and Marcona, served with brioche al tuppo.",
    price: 7.0,
    image: coffee,
  },
  {
    id: "g-fr",
    cat: "Granita",
    name: "Granita di Fragola",
    desc: "Sun-ripened strawberries from the Northshore market.",
    price: 6.75,
    image: coffee,
  },
  {
    id: "p-co",
    cat: "Pastries",
    name: "Cornetto",
    desc: "Italian croissant — flakier, less buttery than its French cousin. Plain or apricot.",
    price: 4.5,
    image: pastries,
  },
  {
    id: "p-sf",
    cat: "Pastries",
    name: "Sfogliatella",
    desc: "Layered shell pastry filled with sweetened ricotta and orange zest.",
    price: 5.25,
    image: pastries,
  },
  {
    id: "p-ca",
    cat: "Pastries",
    name: "Cannolo Siciliano",
    desc: "Filled to order. Ricotta, candied orange, pistachio.",
    price: 5.75,
    image: pastries,
  },
  {
    id: "p-ti",
    cat: "Pastries",
    name: "Tiramisù al Bicchiere",
    desc: "House classic, served in a glass. Mascarpone, espresso-soaked savoiardi, cocoa.",
    price: 6.5,
    image: pastries,
  },
];

export const CATEGORIES = [
  "All",
  "Espresso",
  "Milk Drinks",
  "Granita",
  "Pastries",
];

export const LOCATIONS = [
  {
    name: "Lakeside Mall",
    addr: "3301 Veterans Memorial Blvd,",
    nbhd: " Metairie, LA 70002",
    hours: "Mon–Sun · 6:00am – 9:00pm",
    phone: "(504) 835-3151",
    pill: "Flagship",
    link: "https://424vets.orderpuccinos.com/"
  },
  {
    name: "West Esplanade",
    addr: "4644 W Esplanade Ave",
    nbhd: "Metairie, LA 70004",
    hours: "Mon–Sat · 6:00am – 9:00pm",
    phone: "(504) 309-2646",
    pill: "Drive-thru",
    link: ""
  },
  {
    name: "Veterans Blvd",
    addr: "424 Veterans Memorial Blvd",
    nbhd: "Metairie, LA 70002",
    hours: "Mon–Sun · 6:00am – 9:00pm",
    phone: "(504) 835-3151",
    pill: "Drive-thru",
    link: "https://424vets.orderpuccinos.com/",
  },
  {
    name: "Metairie Road",
    addr: "1801 Dickory Ave",
    nbhd: "Harahan, LA 70123",
    hours: "Mon–Sun · 6:00am – 9:00pm",
    phone: " (504) 304-0210",
    pill: "Drive-thru",
    link: "https://metrd.orderpuccinos.com/"
  },
  {
    name: "Dickory",
    addr: "1801 Dickory Ave",
    nbhd: "Metairie, LA 70001",
    hours: "Mon–Sun · 6:00am – 9:00pm",
    phone: "(504) 373-5450",
    pill: "Drive-thru",
    link: "https://dickoryave.orderpuccinos.com/"
  },
];
